#!/usr/bin/env bash

pushd ~/.config
sudo cp -r hypr ghostty nvim waybar wlogout rofi cava networkmanager-dmenu swaync chromium-flags.conf ../dotfiles/env/.config
popd

pushd $HOME
sudo cp -r .zshrc .zsh_profile .xprofile .tmux.conf dotfiles/env
popd

pushd $HOME/.local
sudo cp -r scripts $HOME/dotfiles/env/.local/
popd

./gitpush
