#!/bin/bash

pushd ~/personal/projects/py_projects/
git add .
git commit -m 'automated dev commit'
git push
popd

pushd ~/dotfiles/
git add .
git commit -m 'automated dev commit'
git push
popd

pushd ~/.config/nvim/
git add .
git commit -m 'automated dev commit'
git push
popd

