#!/bin/bash

# Update package lists
sudo pacman -Syu

# Install Packages
sudo pacman -S nvim

# Copy config files
echo "Copying config files"
sudo cp -r .config .local $HOME

#Install zsh
#echo "installing zsh"
#pushd runs/
#./zsh.sh
#popd
#pushd zsh/
#cp -r .zshrc .zsh .zsh_profile ~/
#popd
#
##install paru
#echo "installing paru"
#pushd runs/
#./paru
#popd
#
##Copy scripts
#echo "copying scripts"
#cp -r .local ~/
#
## install hyprland
#read -p "Do you want to install Hyprland? (Y/N): " choicehyprland
#if [[ "$choicehyprland" =~ ^[Yy]$ ]]; then
#    pushd runs/
#    ./install-hyprland
#    echo "hyprland installation completed"
#else
#    echo "Hyprland installation skipped."
#fi
#
#echo "Package installation and file copy complete!"
