#!/usr/bin/env bash
set -e

git config user.name "1901neetesh"
git config user.email "neeteshjatav11@gmail.com"

gh auth switch -u 1901neetesh >/dev/null

echo "Switched to FRIEND identity (fork repo)"
pwd
