#!/usr/bin/env bash

# use this command if you have systemd-boot instead of grub or for other boot options
# For grub or for other boot options please consider looking online
sudo -E nvim /boot/loader/loader.conf

# For Limine
# sudo -E nvim /boot/limine.conf
