#!/usr/bin/env bash

# Go
sudo pacman -S --noconfirm --needed go
go install github.com/air-verse/air@latest

# sudo pacman -S --noconfirm --needed caddy

# C essentials
sudo pacman -S --noconfirm --needed hyperfine valgrind

# Rust
sudo pacman -S --noconfirm --needed rust-src rust

# Node/Bun
sudo pacman -S --noconfirm nodejs npm
npm config set prefix ~/.local/npm
npm i -g n
n lts
curl -fsSL https://bun.sh/install | bash


